spring:
  application:
    name: discovery-service

server:
  port: 8090 # Port for the discovery service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
