server:
  port: 8050

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: Anayojames
    driver-class-name: org.postgresql.Driver  # Make sure the driver is defined

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

logging:
  level:
    org.springframework: DEBUG
